# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

# Orchestrate or schedule a set of jobs
workflows:
  jobs:
    - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          command: |
            npx husky Install
          name: Install husky
      - run:
          command: |
            npm i
          name: Install package
      - run:
          command: |
            npm run eslint && npm run stylelint
          name: code lint
      - run:
          command: |
            npm run build
          name: Build
      - run:
          command: |
            npm run

      # - store_artifacts:
      #   paths:
      #     - dist
      #     - package.json
      #     - yarn.lock
      #     - app.yaml
  # deploy:
  #   steps:
  #     - checkout
  #     - run:
  #       name: Deploy to Vercel
  #       command: |
  #         git push
