<template>
  <h4>Final Result</h4>
  <Paper class="record">
    <Table :headers="headers" :data="data" />
  </Paper>
</template>
<script lang="ts">
  import { defineComponent } from 'vue';
  import Paper from './Paper.vue';
  import Table from './Table.vue';
  export default defineComponent({
    components: {
      Paper,
      Table,
    },
    data() {
      return {
        headers: [
          'name',
          'A',
          'C',
          'D',
          'PP',
          'NS',
          'Miss',
          'Pro',
          'Time',
          'total',
          'score',
        ],
        data: [
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
        ],
      };
    },
  });
</script>
