<template>
  <h4>Scoreboard</h4>
  <Paper class="record">
    <div style="height: 500px; overflow: auto">
      <table>
        <thead>
          <tr>
            <th>ID:</th>
            <th v-for="(header, id) in headers" :key="id" class="">
              {{ header }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(scores, index) in data" :key="index" class="">
            <td>{{ index + 1 }}</td>
            <td v-for="(score, i) in scores" :key="i" class="">
              {{ score }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </Paper>
</template>

<script lang="ts">
  import { defineComponent } from 'vue';
  import Paper from './Paper.vue';
  // @ts-ignore
  export default defineComponent({
    components: {
      Paper,
    },
    data() {
      return {
        headers: [
          'name',
          'A',
          'C',
          'D',
          'PP',
          'NS',
          'Miss',
          'Pro',
          'Time',
          'total',
          'score',
        ],
        data: [
          {
            name: 'Bensss',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
          {
            name: 'Ben',
            A: 10,
            C: 10,
            D: 10,
            PP: 10,
            NS: 10,
            Miss: 10,
            Pro: 10,
            Time: 10.01,
            total: 1010,
            score: 1001,
          },
        ],
      };
    },
  });
</script>

<style scoped>
  .record {
    overflow: visible;
  }

  table {
    background-color: var(--secound-color);
    width: 100%;
    position: relative;
    text-align: center;
    border-collapse: collapse;
  }

  thead {
    box-shadow: inset 0 4px 20px -10px #000;
  }

  tbody {
    margin-top: 50px;
    color: var(--text-color);
  }

  th,
  td {
    padding: 8px 2px;
  }

  tr:nth-child(odd) {
    background-color: #0002;
  }

  th {
    position: sticky !important;
    position: -webkit-sticky !important;
    background-color: #ccc;
    top: 0;
  }
</style>
